using System.Collections.Generic;

namespace Codecepticon.Modules.VB6
{
    class Vb6Constants
    {
        // This list is from https://docs.microsoft.com/en-us/office/vba/language/reference/user-interface-help/data-type-summary
        public static List<string> DataTypes = new List<string>
        {
            "boolean",
            "byte",
            "collection",
            "currency",
            "date",
            "decimal",
            "double",
            "integer",
            "long",
            "longlong",
            "longptr",
            "object",
            "single",
            "string",
            "variant"
        };

        // This list is from https://docs.microsoft.com/en-us/office/vba/language/reference/constants-visual-basic-for-applications
        public static Dictionary<string, long> Constants = new Dictionary<string, long>
        {
            { "vbCalGreg", 0 },
            { "vbCalHijri", 1 },
            { "vbMethod", 1 },
            { "vbGet", 2 },
            { "vbLet", 4 },
            { "vbSet", 8 },
            { "vbBlack", 0 },
            { "vbRed", 255 },
            { "vbGreen", 65280 },
            { "vbYellow", 65535 },
            { "vbBlue", 16711680 },
            { "vbMagenta", 16711935 },
            { "vbCyan", 16776960 },
            { "vbWhite", 16777215 },
            { "vbUseCompareOption", -1 },
            { "vbBinaryCompare", 0 },
            { "vbTextCompare", 1 },
            { "vbDatabaseCompare", 2 },
            { "vbUseSystem", 0 },
            { "vbSunday", 1 },
            { "vbMonday", 2 },
            { "vbTuesday", 3 },
            { "vbWednesday", 4 },
            { "vbThursday", 5 },
            { "vbFriday", 6 },
            { "vbSaturday", 7 },
            { "VbUseSystemDayOfWeek", 0 },
            { "VbFirstJan1", 1 },
            { "vbFirstFourDays", 2 },
            { "vbFirstFullWeek", 3 },
            { "vbGeneralDate", 0 },
            { "vbLongDate", 1 },
            { "vbShortDate", 2 },
            { "vbLongTime", 3 },
            { "vbShortTime", 4 },
            { "vbNormal", 0 },
            { "vbReadOnly", 1 },
            { "vbHidden", 2 },
            { "vbSystem", 4 },
            { "vbVolume", 8 },
            { "vbDirectory", 16 },
            { "vbArchive", 32 },
            { "vbAlias", 64 },
            { "vbCompressed", 128 },
            { "vbModeless", 0 },
            { "vbModal", 1 },
            { "vbIMEModeNoControl", 0 },
            { "vbIMEModeOn", 1 },
            { "vbIMEModeOff", 2 },
            { "vbIMEModeDisable", 3 },
            { "vbIMEModeHiragana", 4 },
            { "vbIMEModeKatakana", 5 },
            { "vbIMEModeKatakanaHalf", 6 },
            { "vbIMEModeAlphaFull", 7 },
            { "vbIMEModeAlpha", 8 },
            { "vbIMEModeHangulFull", 9 },
            { "vbIMEModeHangul", 10 },
            { "vbKeyLButton", 1 },
            { "vbKeyRButton", 2 },
            { "vbKeyCancel", 3 },
            { "vbKeyMButton", 4 },
            { "vbKeyBack", 8 },
            { "vbKeyTab", 9 },
            { "vbKeyClear", 12 },
            { "vbKeyReturn", 13 },
            { "vbKeyShift", 16 },
            { "vbKeyControl", 17 },
            { "vbKeyMenu", 18 },
            { "vbKeyPause", 19 },
            { "vbKeyCapital", 20 },
            { "vbKeyEscape", 27 },
            { "vbKeySpace", 32 },
            { "vbKeyPageUp", 33 },
            { "vbKeyPageDown", 34 },
            { "vbKeyEnd", 35 },
            { "vbKeyHome", 36 },
            { "vbKeyLeft", 37 },
            { "vbKeyUp", 38 },
            { "vbKeyRight", 39 },
            { "vbKeyDown", 40 },
            { "vbKeySelect", 41 },
            { "vbKeyPrint", 42 },
            { "vbKeyExecute", 43 },
            { "vbKeySnapshot", 44 },
            { "vbKeyInsert", 45 },
            { "vbKeyDelete", 46 },
            { "vbKeyHelp", 47 },
            { "vbKeyNumlock", 144 },
            { "vbKeyA", 65 },
            { "vbKeyB", 66 },
            { "vbKeyC", 67 },
            { "vbKeyD", 68 },
            { "vbKeyE", 69 },
            { "vbKeyF", 70 },
            { "vbKeyG", 71 },
            { "vbKeyH", 72 },
            { "vbKeyI", 73 },
            { "vbKeyJ", 74 },
            { "vbKeyK", 75 },
            { "vbKeyL", 76 },
            { "vbKeyM", 77 },
            { "vbKeyN", 78 },
            { "vbKeyO", 79 },
            { "vbKeyP", 80 },
            { "vbKeyQ", 81 },
            { "vbKeyR", 82 },
            { "vbKeyS", 83 },
            { "vbKeyT", 84 },
            { "vbKeyU", 85 },
            { "vbKeyV", 86 },
            { "vbKeyW", 87 },
            { "vbKeyX", 88 },
            { "vbKeyY", 89 },
            { "vbKeyZ", 90 },
            { "vbKey0", 48 },
            { "vbKey1", 49 },
            { "vbKey2", 50 },
            { "vbKey3", 51 },
            { "vbKey4", 52 },
            { "vbKey5", 53 },
            { "vbKey6", 54 },
            { "vbKey7", 55 },
            { "vbKey8", 56 },
            { "vbKey9", 57 },
            { "vbKeyNumpad0", 96 },
            { "vbKeyNumpad1", 97 },
            { "vbKeyNumpad2", 98 },
            { "vbKeyNumpad3", 99 },
            { "vbKeyNumpad4", 100 },
            { "vbKeyNumpad5", 101 },
            { "vbKeyNumpad6", 102 },
            { "vbKeyNumpad7", 103 },
            { "vbKeyNumpad8", 104 },
            { "vbKeyNumpad9", 105 },
            { "vbKeyMultiply", 106 },
            { "vbKeyAdd", 107 },
            { "vbKeySeparator", 108 },
            { "vbKeySubtract", 109 },
            { "vbKeyDecimal", 110 },
            { "vbKeyDivide", 111 },
            { "vbKeyF1", 112 },
            { "vbKeyF2", 113 },
            { "vbKeyF3", 114 },
            { "vbKeyF4", 115 },
            { "vbKeyF5", 116 },
            { "vbKeyF6", 117 },
            { "vbKeyF7", 118 },
            { "vbKeyF8", 119 },
            { "vbKeyF9", 120 },
            { "vbKeyF10", 121 },
            { "vbKeyF11", 122 },
            { "vbKeyF12", 123 },
            { "vbKeyF13", 124 },
            { "vbKeyF14", 125 },
            { "vbKeyF15", 126 },
            { "vbKeyF16", 127 },
            { "vbObjectError", -2147221504 },
            { "vbOKOnly", 0 },
            { "vbOKCancel", 1 },
            { "vbAbortRetryIgnore", 2 },
            { "vbYesNoCancel", 3 },
            { "vbYesNo", 4 },
            { "vbRetryCancel", 5 },
            { "vbCritical", 16 },
            { "vbQuestion", 32 },
            { "vbExclamation", 48 },
            { "vbInformation", 64 },
            { "vbDefaultButton1", 0 },
            { "vbDefaultButton2", 256 },
            { "vbDefaultButton3", 512 },
            { "vbDefaultButton4", 768 },
            { "vbApplicationModal", 0 },
            { "vbSystemModal", 4096 },
            { "vbMsgBoxHelpButton", 16384 },
            { "VbMsgBoxSetForeground", 65536 },
            { "vbMsgBoxRight", 524288 },
            { "vbMsgBoxRtlReading", 1048576 },
            { "vbOK", 1 },
            { "vbCancel", 2 },
            { "vbAbort", 3 },
            { "vbRetry", 4 },
            { "vbIgnore", 5 },
            { "vbYes", 6 },
            { "vbNo", 7 },
            { "vbFormControlMenu", 0 },
            { "vbFormCode", 1 },
            { "vbAppWindows", 2 },
            { "vbAppTaskManager", 3 },
            { "vbHide", 0 },
            { "vbNormalFocus", 1 },
            { "vbMinimizedFocus", 2 },
            { "vbMaximizedFocus", 3 },
            { "vbNormalNoFocus", 4 },
            { "vbMinimizedNoFocus", 6 },
            { "vbUpperCase", 1 },
            { "vbLowerCase", 2 },
            { "vbProperCase", 3 },
            { "vbWide", 4 },
            { "vbNarrow", 8 },
            { "vbKatakana", 16 },
            { "vbHiragana", 32 },
            { "vbUnicode", 64 },
            { "vbFromUnicode", 128 },
            { "vbScrollBars", 2147483648 },
            { "vbDesktop", 2147483649 },
            { "vbActiveTitleBar", 2147483650 },
            { "vbInactiveTitleBar", 2147483651 },
            { "vbMenuBar", 2147483652 },
            { "vbWindowBackground", 2147483653 },
            { "vbWindowFrame", 2147483654 },
            { "vbMenuText", 2147483655 },
            { "vbWindowText", 2147483656 },
            { "vbTitleBarText", 2147483657 },
            { "vbActiveBorder", 2147483658 },
            { "vbInactiveBorder", 2147483659 },
            { "vbApplicationWorkspace", 2147483660 },
            { "vbHighlight", 2147483661 },
            { "vbHighlightText", 2147483662 },
            { "vbButtonFace", 2147483663 },
            { "vbButtonShadow", 2147483664 },
            { "vbGrayText", 2147483665 },
            { "vbButtonText", 2147483666 },
            { "vbInactiveCaptionText", 2147483667 },
            { "vb3DHighlight", 2147483668 },
            { "vb3DDKShadow", 2147483669 },
            { "vb3DLight", 2147483670 },
            { "vbInfoText", 2147483671 },
            { "vbInfoBackground", 2147483672 },
            { "vbTrue", -1 },
            { "vbFalse", 0 },
            { "vbUseDefault", -2 },

        };

        /*
         * Leaving this here for future reference:
                vbCrLf	Chr(13) + Chr(10)
                vbCr	Chr(13)
                vbLf	Chr(10)
                vbNewLine	Chr(13) + Chr(10)
                vbNullChar	Chr(0)
                vbTab	Chr(9)
                vbBack	Chr(8)
                vbFormFeed	Chr(12)
                vbVerticalTab	Chr(11)
         */
    }
}
